// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.oss.jpa.model;

import com.palmcommerce.oss.jpa.model.SelectPartnerPopedomPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SelectPartnerPopedomPK_Roo_Configurable {
    
    declare @type: SelectPartnerPopedomPK: @Configurable;
    
}
