// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.funds.id.service;

import com.palmcommerce.funds.id.model.LocalAndRemoteSerialRelation;
import com.palmcommerce.funds.id.service.LocalAndRemoteSerialRelationService;
import java.util.List;

privileged aspect LocalAndRemoteSerialRelationService_Roo_Service {
    
    public abstract long LocalAndRemoteSerialRelationService.countAllLocalAndRemoteSerialRelations();    
    public abstract void LocalAndRemoteSerialRelationService.deleteLocalAndRemoteSerialRelation(LocalAndRemoteSerialRelation localAndRemoteSerialRelation);    
    public abstract LocalAndRemoteSerialRelation LocalAndRemoteSerialRelationService.findLocalAndRemoteSerialRelation(Long id);    
    public abstract List<LocalAndRemoteSerialRelation> LocalAndRemoteSerialRelationService.findAllLocalAndRemoteSerialRelations();    
    public abstract List<LocalAndRemoteSerialRelation> LocalAndRemoteSerialRelationService.findLocalAndRemoteSerialRelationEntries(int firstResult, int maxResults);    
    public abstract void LocalAndRemoteSerialRelationService.saveLocalAndRemoteSerialRelation(LocalAndRemoteSerialRelation localAndRemoteSerialRelation);    
    public abstract LocalAndRemoteSerialRelation LocalAndRemoteSerialRelationService.updateLocalAndRemoteSerialRelation(LocalAndRemoteSerialRelation localAndRemoteSerialRelation);    
}
