// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.funds.mock.client.model;

import com.palmcommerce.funds.mock.client.model.Protocol240001;
import com.palmcommerce.funds.mock.client.model.Protocol240001DataOnDemand;
import com.palmcommerce.funds.mock.client.model.Protocol240001IntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Protocol240001IntegrationTest_Roo_IntegrationTest {
    
    declare @type: Protocol240001IntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: Protocol240001IntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: Protocol240001IntegrationTest: @Transactional;
    
    @Autowired
    Protocol240001DataOnDemand Protocol240001IntegrationTest.dod;
    
    @Test
    public void Protocol240001IntegrationTest.testCountProtocol240001s() {
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", dod.getRandomProtocol240001());
        long count = Protocol240001.countProtocol240001s();
        Assert.assertTrue("Counter for 'Protocol240001' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void Protocol240001IntegrationTest.testFindProtocol240001() {
        Protocol240001 obj = dod.getRandomProtocol240001();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to provide an identifier", id);
        obj = Protocol240001.findProtocol240001(id);
        Assert.assertNotNull("Find method for 'Protocol240001' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Protocol240001' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void Protocol240001IntegrationTest.testFindAllProtocol240001s() {
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", dod.getRandomProtocol240001());
        long count = Protocol240001.countProtocol240001s();
        Assert.assertTrue("Too expensive to perform a find all test for 'Protocol240001', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Protocol240001> result = Protocol240001.findAllProtocol240001s();
        Assert.assertNotNull("Find all method for 'Protocol240001' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Protocol240001' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void Protocol240001IntegrationTest.testFindProtocol240001Entries() {
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", dod.getRandomProtocol240001());
        long count = Protocol240001.countProtocol240001s();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Protocol240001> result = Protocol240001.findProtocol240001Entries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Protocol240001' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Protocol240001' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void Protocol240001IntegrationTest.testFlush() {
        Protocol240001 obj = dod.getRandomProtocol240001();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to provide an identifier", id);
        obj = Protocol240001.findProtocol240001(id);
        Assert.assertNotNull("Find method for 'Protocol240001' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProtocol240001(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Protocol240001' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Protocol240001IntegrationTest.testMergeUpdate() {
        Protocol240001 obj = dod.getRandomProtocol240001();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to provide an identifier", id);
        obj = Protocol240001.findProtocol240001(id);
        boolean modified =  dod.modifyProtocol240001(obj);
        Integer currentVersion = obj.getVersion();
        Protocol240001 merged = (Protocol240001)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Protocol240001' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Protocol240001IntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", dod.getRandomProtocol240001());
        Protocol240001 obj = dod.getNewTransientProtocol240001(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Protocol240001' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Protocol240001' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void Protocol240001IntegrationTest.testRemove() {
        Protocol240001 obj = dod.getRandomProtocol240001();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Protocol240001' failed to provide an identifier", id);
        obj = Protocol240001.findProtocol240001(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Protocol240001' with identifier '" + id + "'", Protocol240001.findProtocol240001(id));
    }
    
}
