// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.funds.mock.client.model;

import com.palmcommerce.funds.mock.client.model.Protocol240001IntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Protocol240001IntegrationTest_Roo_Configurable {
    
    declare @type: Protocol240001IntegrationTest: @Configurable;
    
}
