// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserLoginName;
import com.palmcommerce.server.v29.db.UserLoginNameDataOnDemand;
import com.palmcommerce.server.v29.db.UserLoginNameIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserLoginNameIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserLoginNameIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserLoginNameIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserLoginNameIntegrationTest: @Transactional;
    
    @Autowired
    UserLoginNameDataOnDemand UserLoginNameIntegrationTest.dod;
    
    @Test
    public void UserLoginNameIntegrationTest.testCountUserLoginNames() {
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to initialize correctly", dod.getRandomUserLoginName());
        long count = UserLoginName.countUserLoginNames();
        Assert.assertTrue("Counter for 'UserLoginName' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserLoginNameIntegrationTest.testFindUserLoginName() {
        UserLoginName obj = dod.getRandomUserLoginName();
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to initialize correctly", obj);
        String id = obj.getLoginName();
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to provide an identifier", id);
        obj = UserLoginName.findUserLoginName(id);
        Assert.assertNotNull("Find method for 'UserLoginName' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserLoginName' returned the incorrect identifier", id, obj.getLoginName());
    }
    
    @Test
    public void UserLoginNameIntegrationTest.testFindAllUserLoginNames() {
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to initialize correctly", dod.getRandomUserLoginName());
        long count = UserLoginName.countUserLoginNames();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserLoginName', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserLoginName> result = UserLoginName.findAllUserLoginNames();
        Assert.assertNotNull("Find all method for 'UserLoginName' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserLoginName' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserLoginNameIntegrationTest.testFindUserLoginNameEntries() {
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to initialize correctly", dod.getRandomUserLoginName());
        long count = UserLoginName.countUserLoginNames();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserLoginName> result = UserLoginName.findUserLoginNameEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserLoginName' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserLoginName' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserLoginNameIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to initialize correctly", dod.getRandomUserLoginName());
        UserLoginName obj = dod.getNewTransientUserLoginName(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserLoginName' identifier to be null", obj.getLoginName());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserLoginName' identifier to no longer be null", obj.getLoginName());
    }
    
    @Test
    public void UserLoginNameIntegrationTest.testRemove() {
        UserLoginName obj = dod.getRandomUserLoginName();
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to initialize correctly", obj);
        String id = obj.getLoginName();
        Assert.assertNotNull("Data on demand for 'UserLoginName' failed to provide an identifier", id);
        obj = UserLoginName.findUserLoginName(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserLoginName' with identifier '" + id + "'", UserLoginName.findUserLoginName(id));
    }
    
}
