// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserIdentifyDataOnDemand;
import com.palmcommerce.server.v29.db.UserIdentifyIntegrationTest;
import com.palmcommerce.server.v29.service.UserIdentifyService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserIdentifyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserIdentifyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserIdentifyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserIdentifyIntegrationTest: @Transactional;
    
    @Autowired
    UserIdentifyDataOnDemand UserIdentifyIntegrationTest.dod;
    
    @Autowired
    UserIdentifyService UserIdentifyIntegrationTest.userIdentifyService;
    
    @Test
    public void UserIdentifyIntegrationTest.testCountAllUserIdentifys() {
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to initialize correctly", dod.getRandomUserIdentify());
        long count = userIdentifyService.countAllUserIdentifys();
        Assert.assertTrue("Counter for 'UserIdentify' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserIdentifyIntegrationTest.testFindUserIdentify() {
        UserIdentify obj = dod.getRandomUserIdentify();
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to initialize correctly", obj);
        String id = obj.getUserId();
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to provide an identifier", id);
        obj = userIdentifyService.findUserIdentify(id);
        Assert.assertNotNull("Find method for 'UserIdentify' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserIdentify' returned the incorrect identifier", id, obj.getUserId());
    }
    
    @Test
    public void UserIdentifyIntegrationTest.testFindAllUserIdentifys() {
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to initialize correctly", dod.getRandomUserIdentify());
        long count = userIdentifyService.countAllUserIdentifys();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserIdentify', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserIdentify> result = userIdentifyService.findAllUserIdentifys();
        Assert.assertNotNull("Find all method for 'UserIdentify' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserIdentify' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserIdentifyIntegrationTest.testFindUserIdentifyEntries() {
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to initialize correctly", dod.getRandomUserIdentify());
        long count = userIdentifyService.countAllUserIdentifys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserIdentify> result = userIdentifyService.findUserIdentifyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserIdentify' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserIdentify' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserIdentifyIntegrationTest.testSaveUserIdentify() {
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to initialize correctly", dod.getRandomUserIdentify());
        UserIdentify obj = dod.getNewTransientUserIdentify(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserIdentify' identifier to be null", obj.getUserId());
        userIdentifyService.saveUserIdentify(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'UserIdentify' identifier to no longer be null", obj.getUserId());
    }
    
    @Test
    public void UserIdentifyIntegrationTest.testDeleteUserIdentify() {
        UserIdentify obj = dod.getRandomUserIdentify();
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to initialize correctly", obj);
        String id = obj.getUserId();
        Assert.assertNotNull("Data on demand for 'UserIdentify' failed to provide an identifier", id);
        obj = userIdentifyService.findUserIdentify(id);
        userIdentifyService.deleteUserIdentify(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'UserIdentify' with identifier '" + id + "'", userIdentifyService.findUserIdentify(id));
    }
    
}
