// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserIdentify;
import com.palmcommerce.server.v29.db.UserIdentifyDataOnDemand;
import com.palmcommerce.server.v29.service.UserIdentifyService;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UserIdentifyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserIdentifyDataOnDemand: @Component;
    
    private Random UserIdentifyDataOnDemand.rnd = new SecureRandom();
    
    private List<UserIdentify> UserIdentifyDataOnDemand.data;
    
    @Autowired
    UserIdentifyService UserIdentifyDataOnDemand.userIdentifyService;
    
    public UserIdentify UserIdentifyDataOnDemand.getNewTransientUserIdentify(int index) {
        UserIdentify obj = new UserIdentify();
        setBankBranches(obj, index);
        setBankCity(obj, index);
        setBankProvince(obj, index);
        setBankcard(obj, index);
        setBankname(obj, index);
        setBirthday(obj, index);
        setCardNo(obj, index);
        setCardType(obj, index);
        setCityAddress(obj, index);
        setCreateTime(obj, index);
        setEducation(obj, index);
        setGender(obj, index);
        setIsMarry(obj, index);
        setLevelType(obj, index);
        setProfession(obj, index);
        setProvinceAddress(obj, index);
        setRealName(obj, index);
        setStatus(obj, index);
        setUpdateTime(obj, index);
        return obj;
    }
    
    public void UserIdentifyDataOnDemand.setBankBranches(UserIdentify obj, int index) {
        String bankBranches = "bankBranches_" + index;
        if (bankBranches.length() > 100) {
            bankBranches = bankBranches.substring(0, 100);
        }
        obj.setBankBranches(bankBranches);
    }
    
    public void UserIdentifyDataOnDemand.setBankCity(UserIdentify obj, int index) {
        String bankCity = "bankCity_" + index;
        if (bankCity.length() > 50) {
            bankCity = bankCity.substring(0, 50);
        }
        obj.setBankCity(bankCity);
    }
    
    public void UserIdentifyDataOnDemand.setBankProvince(UserIdentify obj, int index) {
        String bankProvince = "bankProvince_" + index;
        if (bankProvince.length() > 50) {
            bankProvince = bankProvince.substring(0, 50);
        }
        obj.setBankProvince(bankProvince);
    }
    
    public void UserIdentifyDataOnDemand.setBankcard(UserIdentify obj, int index) {
        String bankcard = "bankcard_" + index;
        if (bankcard.length() > 30) {
            bankcard = bankcard.substring(0, 30);
        }
        obj.setBankcard(bankcard);
    }
    
    public void UserIdentifyDataOnDemand.setBankname(UserIdentify obj, int index) {
        String bankname = "bankname_" + index;
        if (bankname.length() > 30) {
            bankname = bankname.substring(0, 30);
        }
        obj.setBankname(bankname);
    }
    
    public void UserIdentifyDataOnDemand.setBirthday(UserIdentify obj, int index) {
        String birthday = "birthday_" + index;
        if (birthday.length() > 10) {
            birthday = birthday.substring(0, 10);
        }
        obj.setBirthday(birthday);
    }
    
    public void UserIdentifyDataOnDemand.setCardNo(UserIdentify obj, int index) {
        String cardNo = "cardNo_" + index;
        if (cardNo.length() > 30) {
            cardNo = cardNo.substring(0, 30);
        }
        obj.setCardNo(cardNo);
    }
    
    public void UserIdentifyDataOnDemand.setCardType(UserIdentify obj, int index) {
        String cardType = "c" + index;
        if (cardType.length() > 2) {
            cardType = cardType.substring(0, 2);
        }
        obj.setCardType(cardType);
    }
    
    public void UserIdentifyDataOnDemand.setCityAddress(UserIdentify obj, int index) {
        String cityAddress = "cityAddress_" + index;
        if (cityAddress.length() > 50) {
            cityAddress = cityAddress.substring(0, 50);
        }
        obj.setCityAddress(cityAddress);
    }
    
    public void UserIdentifyDataOnDemand.setCreateTime(UserIdentify obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void UserIdentifyDataOnDemand.setEducation(UserIdentify obj, int index) {
        String education = "education_" + index;
        if (education.length() > 50) {
            education = education.substring(0, 50);
        }
        obj.setEducation(education);
    }
    
    public void UserIdentifyDataOnDemand.setGender(UserIdentify obj, int index) {
        String gender = "gender_" + index;
        if (gender.length() > 10) {
            gender = gender.substring(0, 10);
        }
        obj.setGender(gender);
    }
    
    public void UserIdentifyDataOnDemand.setIsMarry(UserIdentify obj, int index) {
        String isMarry = "isMarry_" + index;
        if (isMarry.length() > 10) {
            isMarry = isMarry.substring(0, 10);
        }
        obj.setIsMarry(isMarry);
    }
    
    public void UserIdentifyDataOnDemand.setLevelType(UserIdentify obj, int index) {
        BigDecimal levelType = BigDecimal.valueOf(index);
        obj.setLevelType(levelType);
    }
    
    public void UserIdentifyDataOnDemand.setProfession(UserIdentify obj, int index) {
        String profession = "profession_" + index;
        if (profession.length() > 50) {
            profession = profession.substring(0, 50);
        }
        obj.setProfession(profession);
    }
    
    public void UserIdentifyDataOnDemand.setProvinceAddress(UserIdentify obj, int index) {
        String provinceAddress = "provinceAddress_" + index;
        if (provinceAddress.length() > 50) {
            provinceAddress = provinceAddress.substring(0, 50);
        }
        obj.setProvinceAddress(provinceAddress);
    }
    
    public void UserIdentifyDataOnDemand.setRealName(UserIdentify obj, int index) {
        String realName = "realName_" + index;
        if (realName.length() > 20) {
            realName = realName.substring(0, 20);
        }
        obj.setRealName(realName);
    }
    
    public void UserIdentifyDataOnDemand.setStatus(UserIdentify obj, int index) {
        BigDecimal status = BigDecimal.valueOf(index);
        obj.setStatus(status);
    }
    
    public void UserIdentifyDataOnDemand.setUpdateTime(UserIdentify obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public UserIdentify UserIdentifyDataOnDemand.getSpecificUserIdentify(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserIdentify obj = data.get(index);
        String id = obj.getUserId();
        return userIdentifyService.findUserIdentify(id);
    }
    
    public UserIdentify UserIdentifyDataOnDemand.getRandomUserIdentify() {
        init();
        UserIdentify obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getUserId();
        return userIdentifyService.findUserIdentify(id);
    }
    
    public boolean UserIdentifyDataOnDemand.modifyUserIdentify(UserIdentify obj) {
        return false;
    }
    
    public void UserIdentifyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = userIdentifyService.findUserIdentifyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserIdentify' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserIdentify>();
        for (int i = 0; i < 10; i++) {
            UserIdentify obj = getNewTransientUserIdentify(i);
            try {
                userIdentifyService.saveUserIdentify(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
