// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserAccountCancle;
import com.palmcommerce.server.v29.db.UserAccountCancleDataOnDemand;
import com.palmcommerce.server.v29.db.UserAccountCancleIntegrationTest;
import com.palmcommerce.server.v29.db.UserAccountCanclePK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAccountCancleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAccountCancleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAccountCancleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAccountCancleIntegrationTest: @Transactional;
    
    @Autowired
    UserAccountCancleDataOnDemand UserAccountCancleIntegrationTest.dod;
    
    @Test
    public void UserAccountCancleIntegrationTest.testCountUserAccountCancles() {
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to initialize correctly", dod.getRandomUserAccountCancle());
        long count = UserAccountCancle.countUserAccountCancles();
        Assert.assertTrue("Counter for 'UserAccountCancle' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAccountCancleIntegrationTest.testFindUserAccountCancle() {
        UserAccountCancle obj = dod.getRandomUserAccountCancle();
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to initialize correctly", obj);
        UserAccountCanclePK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to provide an identifier", id);
        obj = UserAccountCancle.findUserAccountCancle(id);
        Assert.assertNotNull("Find method for 'UserAccountCancle' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAccountCancle' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAccountCancleIntegrationTest.testFindAllUserAccountCancles() {
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to initialize correctly", dod.getRandomUserAccountCancle());
        long count = UserAccountCancle.countUserAccountCancles();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAccountCancle', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAccountCancle> result = UserAccountCancle.findAllUserAccountCancles();
        Assert.assertNotNull("Find all method for 'UserAccountCancle' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAccountCancle' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAccountCancleIntegrationTest.testFindUserAccountCancleEntries() {
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to initialize correctly", dod.getRandomUserAccountCancle());
        long count = UserAccountCancle.countUserAccountCancles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAccountCancle> result = UserAccountCancle.findUserAccountCancleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAccountCancle' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAccountCancle' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAccountCancleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to initialize correctly", dod.getRandomUserAccountCancle());
        UserAccountCancle obj = dod.getNewTransientUserAccountCancle(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserAccountCancle' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAccountCancleIntegrationTest.testRemove() {
        UserAccountCancle obj = dod.getRandomUserAccountCancle();
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to initialize correctly", obj);
        UserAccountCanclePK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccountCancle' failed to provide an identifier", id);
        obj = UserAccountCancle.findUserAccountCancle(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAccountCancle' with identifier '" + id + "'", UserAccountCancle.findUserAccountCancle(id));
    }
    
}
