// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserAccountLog105DataOnDemand;
import com.palmcommerce.server.v29.db.UserAccountLog105IntegrationTest;
import com.palmcommerce.server.v29.service.UserAccountLogService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAccountLog105IntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAccountLog105IntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAccountLog105IntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAccountLog105IntegrationTest: @Transactional;
    
    @Autowired
    UserAccountLog105DataOnDemand UserAccountLog105IntegrationTest.dod;
    
    @Autowired
    UserAccountLogService UserAccountLog105IntegrationTest.userAccountLogService;
    
    @Test
    public void UserAccountLog105IntegrationTest.testCountAllUserAccountLog105s() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to initialize correctly", dod.getRandomUserAccountLog105());
        long count = userAccountLogService.countAllUserAccountLog105s();
        Assert.assertTrue("Counter for 'UserAccountLog105' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAccountLog105IntegrationTest.testFindUserAccountLog105() {
        UserAccountLog105 obj = dod.getRandomUserAccountLog105();
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to initialize correctly", obj);
        String id = obj.getLogId();
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to provide an identifier", id);
        obj = userAccountLogService.findUserAccountLog105(id);
        Assert.assertNotNull("Find method for 'UserAccountLog105' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAccountLog105' returned the incorrect identifier", id, obj.getLogId());
    }
    
    @Test
    public void UserAccountLog105IntegrationTest.testFindAllUserAccountLog105s() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to initialize correctly", dod.getRandomUserAccountLog105());
        long count = userAccountLogService.countAllUserAccountLog105s();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAccountLog105', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAccountLog105> result = userAccountLogService.findAllUserAccountLog105s();
        Assert.assertNotNull("Find all method for 'UserAccountLog105' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAccountLog105' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAccountLog105IntegrationTest.testFindUserAccountLog105Entries() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to initialize correctly", dod.getRandomUserAccountLog105());
        long count = userAccountLogService.countAllUserAccountLog105s();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAccountLog105> result = userAccountLogService.findUserAccountLog105Entries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAccountLog105' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAccountLog105' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAccountLog105IntegrationTest.testSaveUserAccountLog105() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to initialize correctly", dod.getRandomUserAccountLog105());
        UserAccountLog105 obj = dod.getNewTransientUserAccountLog105(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserAccountLog105' identifier to be null", obj.getLogId());
        userAccountLogService.saveUserAccountLog105(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'UserAccountLog105' identifier to no longer be null", obj.getLogId());
    }
    
    @Test
    public void UserAccountLog105IntegrationTest.testDeleteUserAccountLog105() {
        UserAccountLog105 obj = dod.getRandomUserAccountLog105();
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to initialize correctly", obj);
        String id = obj.getLogId();
        Assert.assertNotNull("Data on demand for 'UserAccountLog105' failed to provide an identifier", id);
        obj = userAccountLogService.findUserAccountLog105(id);
        userAccountLogService.deleteUserAccountLog105(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAccountLog105' with identifier '" + id + "'", userAccountLogService.findUserAccountLog105(id));
    }
    
}
