// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserAccountLog106DataOnDemand;
import com.palmcommerce.server.v29.db.UserAccountLog106IntegrationTest;
import com.palmcommerce.server.v29.service.UserAccountLogService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAccountLog106IntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAccountLog106IntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAccountLog106IntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAccountLog106IntegrationTest: @Transactional;
    
    @Autowired
    UserAccountLog106DataOnDemand UserAccountLog106IntegrationTest.dod;
    
    @Autowired
    UserAccountLogService UserAccountLog106IntegrationTest.userAccountLogService;
    
    @Test
    public void UserAccountLog106IntegrationTest.testCountAllUserAccountLog106s() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to initialize correctly", dod.getRandomUserAccountLog106());
        long count = userAccountLogService.countAllUserAccountLog106s();
        Assert.assertTrue("Counter for 'UserAccountLog106' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAccountLog106IntegrationTest.testFindUserAccountLog106() {
        UserAccountLog106 obj = dod.getRandomUserAccountLog106();
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to initialize correctly", obj);
        String id = obj.getLogId();
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to provide an identifier", id);
        obj = userAccountLogService.findUserAccountLog106(id);
        Assert.assertNotNull("Find method for 'UserAccountLog106' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAccountLog106' returned the incorrect identifier", id, obj.getLogId());
    }
    
    @Test
    public void UserAccountLog106IntegrationTest.testFindAllUserAccountLog106s() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to initialize correctly", dod.getRandomUserAccountLog106());
        long count = userAccountLogService.countAllUserAccountLog106s();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAccountLog106', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAccountLog106> result = userAccountLogService.findAllUserAccountLog106s();
        Assert.assertNotNull("Find all method for 'UserAccountLog106' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAccountLog106' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAccountLog106IntegrationTest.testFindUserAccountLog106Entries() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to initialize correctly", dod.getRandomUserAccountLog106());
        long count = userAccountLogService.countAllUserAccountLog106s();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAccountLog106> result = userAccountLogService.findUserAccountLog106Entries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAccountLog106' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAccountLog106' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAccountLog106IntegrationTest.testSaveUserAccountLog106() {
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to initialize correctly", dod.getRandomUserAccountLog106());
        UserAccountLog106 obj = dod.getNewTransientUserAccountLog106(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserAccountLog106' identifier to be null", obj.getLogId());
        userAccountLogService.saveUserAccountLog106(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'UserAccountLog106' identifier to no longer be null", obj.getLogId());
    }
    
    @Test
    public void UserAccountLog106IntegrationTest.testDeleteUserAccountLog106() {
        UserAccountLog106 obj = dod.getRandomUserAccountLog106();
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to initialize correctly", obj);
        String id = obj.getLogId();
        Assert.assertNotNull("Data on demand for 'UserAccountLog106' failed to provide an identifier", id);
        obj = userAccountLogService.findUserAccountLog106(id);
        userAccountLogService.deleteUserAccountLog106(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAccountLog106' with identifier '" + id + "'", userAccountLogService.findUserAccountLog106(id));
    }
    
}
