// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserAccountDetailCancle;
import com.palmcommerce.server.v29.db.UserAccountDetailCancleDataOnDemand;
import com.palmcommerce.server.v29.db.UserAccountDetailCanclePK;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserAccountDetailCancleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserAccountDetailCancleDataOnDemand: @Component;
    
    private Random UserAccountDetailCancleDataOnDemand.rnd = new SecureRandom();
    
    private List<UserAccountDetailCancle> UserAccountDetailCancleDataOnDemand.data;
    
    public UserAccountDetailCancle UserAccountDetailCancleDataOnDemand.getNewTransientUserAccountDetailCancle(int index) {
        UserAccountDetailCancle obj = new UserAccountDetailCancle();
        setEmbeddedIdClass(obj, index);
        return obj;
    }
    
    public void UserAccountDetailCancleDataOnDemand.setEmbeddedIdClass(UserAccountDetailCancle obj, int index) {
        String userId = "userId_" + index;
        if (userId.length() > 30) {
            userId = new Random().nextInt(10) + userId.substring(1, 30);
        }
        String partnerId = "partnerId_" + index;
        if (partnerId.length() > 30) {
            partnerId = new Random().nextInt(10) + partnerId.substring(1, 30);
        }
        BigDecimal throwNum = BigDecimal.valueOf(index);
        BigDecimal throwAccount = BigDecimal.valueOf(index);
        if (throwAccount.compareTo(new BigDecimal("9999999999999.99")) == 1) {
            throwAccount = new BigDecimal("9999999999999.99");
        }
        BigDecimal prizeNum = BigDecimal.valueOf(index);
        BigDecimal prizeAccount = BigDecimal.valueOf(index);
        if (prizeAccount.compareTo(new BigDecimal("9999999999999.99")) == 1) {
            prizeAccount = new BigDecimal("9999999999999.99");
        }
        BigDecimal chargeNum = BigDecimal.valueOf(index);
        BigDecimal chargeAccount = BigDecimal.valueOf(index);
        if (chargeAccount.compareTo(new BigDecimal("9999999999999.99")) == 1) {
            chargeAccount = new BigDecimal("9999999999999.99");
        }
        BigDecimal encashNum = BigDecimal.valueOf(index);
        BigDecimal encashAccount = BigDecimal.valueOf(index);
        if (encashAccount.compareTo(new BigDecimal("9999999999999.99")) == 1) {
            encashAccount = new BigDecimal("9999999999999.99");
        }
        BigDecimal bigPrizeNum = BigDecimal.valueOf(index);
        BigDecimal bigPrizeAccount = BigDecimal.valueOf(index);
        if (bigPrizeAccount.compareTo(new BigDecimal("9999999999999.99")) == 1) {
            bigPrizeAccount = new BigDecimal("9999999999999.99");
        }
        
        UserAccountDetailCanclePK embeddedIdClass = new UserAccountDetailCanclePK(userId, partnerId, throwNum, throwAccount, prizeNum, prizeAccount, chargeNum, chargeAccount, encashNum, encashAccount, bigPrizeNum, bigPrizeAccount);
        obj.setId(embeddedIdClass);
    }
    
    public UserAccountDetailCancle UserAccountDetailCancleDataOnDemand.getSpecificUserAccountDetailCancle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserAccountDetailCancle obj = data.get(index);
        UserAccountDetailCanclePK id = obj.getId();
        return UserAccountDetailCancle.findUserAccountDetailCancle(id);
    }
    
    public UserAccountDetailCancle UserAccountDetailCancleDataOnDemand.getRandomUserAccountDetailCancle() {
        init();
        UserAccountDetailCancle obj = data.get(rnd.nextInt(data.size()));
        UserAccountDetailCanclePK id = obj.getId();
        return UserAccountDetailCancle.findUserAccountDetailCancle(id);
    }
    
    public boolean UserAccountDetailCancleDataOnDemand.modifyUserAccountDetailCancle(UserAccountDetailCancle obj) {
        return false;
    }
    
    public void UserAccountDetailCancleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserAccountDetailCancle.findUserAccountDetailCancleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserAccountDetailCancle' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserAccountDetailCancle>();
        for (int i = 0; i < 10; i++) {
            UserAccountDetailCancle obj = getNewTransientUserAccountDetailCancle(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
