// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserOrder104;
import com.palmcommerce.server.v29.db.UserOrder104DataOnDemand;
import com.palmcommerce.server.v29.db.UserOrder104IntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserOrder104IntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserOrder104IntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserOrder104IntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserOrder104IntegrationTest: @Transactional;
    
    @Autowired
    UserOrder104DataOnDemand UserOrder104IntegrationTest.dod;
    
    @Test
    public void UserOrder104IntegrationTest.testCountUserOrder104s() {
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to initialize correctly", dod.getRandomUserOrder104());
        long count = UserOrder104.countUserOrder104s();
        Assert.assertTrue("Counter for 'UserOrder104' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserOrder104IntegrationTest.testFindUserOrder104() {
        UserOrder104 obj = dod.getRandomUserOrder104();
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to initialize correctly", obj);
        String id = obj.getOrderId();
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to provide an identifier", id);
        obj = UserOrder104.findUserOrder104(id);
        Assert.assertNotNull("Find method for 'UserOrder104' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserOrder104' returned the incorrect identifier", id, obj.getOrderId());
    }
    
    @Test
    public void UserOrder104IntegrationTest.testFindAllUserOrder104s() {
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to initialize correctly", dod.getRandomUserOrder104());
        long count = UserOrder104.countUserOrder104s();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserOrder104', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserOrder104> result = UserOrder104.findAllUserOrder104s();
        Assert.assertNotNull("Find all method for 'UserOrder104' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserOrder104' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserOrder104IntegrationTest.testFindUserOrder104Entries() {
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to initialize correctly", dod.getRandomUserOrder104());
        long count = UserOrder104.countUserOrder104s();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserOrder104> result = UserOrder104.findUserOrder104Entries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserOrder104' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserOrder104' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserOrder104IntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to initialize correctly", dod.getRandomUserOrder104());
        UserOrder104 obj = dod.getNewTransientUserOrder104(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserOrder104' identifier to be null", obj.getOrderId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserOrder104' identifier to no longer be null", obj.getOrderId());
    }
    
    @Test
    public void UserOrder104IntegrationTest.testRemove() {
        UserOrder104 obj = dod.getRandomUserOrder104();
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to initialize correctly", obj);
        String id = obj.getOrderId();
        Assert.assertNotNull("Data on demand for 'UserOrder104' failed to provide an identifier", id);
        obj = UserOrder104.findUserOrder104(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserOrder104' with identifier '" + id + "'", UserOrder104.findUserOrder104(id));
    }
    
}
