// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserAccountCanclePK;
import com.palmcommerce.server.v29.db.UserAccountDataOnDemand;
import com.palmcommerce.server.v29.db.UserAccountIntegrationTest;
import com.palmcommerce.server.v29.service.UserAccountService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAccountIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAccountIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAccountIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAccountIntegrationTest: @Transactional;
    
    @Autowired
    UserAccountDataOnDemand UserAccountIntegrationTest.dod;
    
    @Autowired
    UserAccountService UserAccountIntegrationTest.userAccountService;
    
    @Test
    public void UserAccountIntegrationTest.testCountAllUserAccounts() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        long count = userAccountService.countAllUserAccounts();
        Assert.assertTrue("Counter for 'UserAccount' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAccountIntegrationTest.testFindUserAccount() {
        UserAccount obj = dod.getRandomUserAccount();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", obj);
        UserAccountCanclePK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide an identifier", id);
        obj = userAccountService.findUserAccount(id);
        Assert.assertNotNull("Find method for 'UserAccount' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAccount' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAccountIntegrationTest.testFindAllUserAccounts() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        long count = userAccountService.countAllUserAccounts();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAccount', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAccount> result = userAccountService.findAllUserAccounts();
        Assert.assertNotNull("Find all method for 'UserAccount' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAccount' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAccountIntegrationTest.testFindUserAccountEntries() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        long count = userAccountService.countAllUserAccounts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAccount> result = userAccountService.findUserAccountEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAccount' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAccount' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAccountIntegrationTest.testSaveUserAccount() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        UserAccount obj = dod.getNewTransientUserAccount(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide a new transient entity", obj);
        userAccountService.saveUserAccount(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'UserAccount' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAccountIntegrationTest.testDeleteUserAccount() {
        UserAccount obj = dod.getRandomUserAccount();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", obj);
        UserAccountCanclePK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide an identifier", id);
        obj = userAccountService.findUserAccount(id);
        userAccountService.deleteUserAccount(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAccount' with identifier '" + id + "'", userAccountService.findUserAccount(id));
    }
    
}
