// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserOrder102DataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserOrder102DataOnDemand_Roo_Configurable {
    
    declare @type: UserOrder102DataOnDemand: @Configurable;
    
}
