// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.funds.mock.client.model;

import com.palmcommerce.funds.mock.client.model.Protocol240002;
import javax.persistence.Entity;

privileged aspect Protocol240002_Roo_Jpa_Entity {
    
    declare @type: Protocol240002: @Entity;
    
}
