// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserAccountDetailCancle;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserAccountDetailCancle_Roo_Configurable {
    
    declare @type: UserAccountDetailCancle: @Configurable;
    
}
