// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.palmcommerce.server.v29.db;

import com.palmcommerce.server.v29.db.UserThirdPayPK;
import java.io.Serializable;

privileged aspect UserThirdPayPK_Roo_Serializable {
    
    declare parents: UserThirdPayPK implements Serializable;
    
    private static final long UserThirdPayPK.serialVersionUID = 1L;
    
}
